import images from "./image";
const data = [
  {
    id: 1,
    title: "아메리카노",
    price: 2500,
    img: images.americano,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 2,
    title: "카페라떼",
    price: 3000,
    img: images.latte,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "카라멜 시럽", price: 300 },
      { id: 4, name: "두유 변경", price: 500 },
    ],
  },
  {
    id: 3,
    title: "바닐라라떼",
    price: 3500,
    img: images.vanillaLatte,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "아몬드 우유 변경", price: 500 },
      { id: 4, name: "카라멜 시럽 추가", price: 300 },
    ],
  },
  {
    id: 4,
    title: "돌체라떼",
    price: 4000,
    img: images.dolceLatte,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "아몬드 우유로 변경", price: 500 },
      { id: 4, name: "카라멜 시럽 추가", price: 300 },
      { id: 5, name: "초콜릿 시럽 추가", price: 300 },
    ],
  },
  {
    id: 5,
    title: "코코넛라떼",
    price: 4000,
    img: images.coconutLatte,
    category: "커피",
    icecreamTopping: 0,
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "아몬드 우유로 변경", price: 500 },
      { id: 4, name: "코코넛 시럽 추가", price: 400 },
    ],
  },
  {
    id: 6,
    title: "카푸치노",
    price: 3000,
    img: images.cappuccino,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "시나몬 추가", price: 200 },
    ],
  },
  {
    id: 7,
    title: "카라멜마키아또",
    price: 3500,
    img: images.caramel,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "카라멜 시럽 추가", price: 300 },
      { id: 4, name: "휘핑크림 추가", price: 400 },
    ],
  },
  {
    id: 8,
    title: "플랫화이트",
    price: 3000,
    img: images.flatWhite,
    category: "커피",
    coffeeSize: ["short", "tall", "grande", "venti"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "샷 추가", price: 500 },
      { id: 2, name: "디카페인으로 변경", price: 500 },
      { id: 3, name: "카라멜 시럽", price: 300 },
      { id: 4, name: "휘핑크림 추가", price: 400 },
    ],
  },
  {
    id: 9,
    title: "구아바모히또",
    price: 3500,
    img: images.mojito,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "민트잎 추가", price: 100 },
      { id: 2, name: "레몬 조각 추가", price: 150 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 10,
    title: "레몬에이드",
    price: 3000,
    img: images.lemon,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "레몬 조각 추가", price: 150 },
      { id: 2, name: "민트잎 추가", price: 100 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 11,
    title: "자몽에이드",
    price: 3000,
    img: images.grapefruit,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "자몽 조각 추가", price: 200 },
      { id: 2, name: "민트잎 추가", price: 100 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 12,
    title: "청포도에이드",
    price: 3000,
    img: images.greengrape,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "청포도 조각 추가", price: 200 },
      { id: 2, name: "레몬 추가", price: 300 },
      { id: 3, name: "민트잎 추가", price: 100 },
      { id: 4, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 13,
    title: "체리에이드",
    price: 3000,
    img: images.cherry,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "체리 조각 추가", price: 200 },
      { id: 2, name: "민트잎 추가", price: 300 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 14,
    title: "키위에이드",
    price: 3000,
    img: images.kiwi,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "키위 조각 추가", price: 200 },
      { id: 2, name: "민트 추가", price: 300 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 15,
    title: "패션코코에이드",
    price: 3500,
    img: images.passioncoco,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "패션프루트 조각 추가", price: 200 },
      { id: 2, name: "민트잎 추가", price: 300 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 16,
    title: "리치티에이드",
    price: 3000,
    img: images.lycheetea,
    category: "에이드",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "리치 조각 추가", price: 200 },
      { id: 2, name: "민트잎 추가", price: 300 },
      { id: 3, name: "얼음 추가", price: 0 },
    ],
  },
  {
    id: 17,
    title: "플레인요거트스무디",
    price: 3500,
    img: images.plainSm,
    category: "스무디",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "과일 추가", price: 200 },
      { id: 2, name: "꿀 추가", price: 150 },
      { id: 3, name: "치아씨드 추가", price: 200 },
      { id: 4, name: "아몬드 슬라이스 추가", price: 250 },
    ],
  },
  {
    id: 18,
    title: "딸기스무디",
    price: 3500,
    img: images.strawberrySm,
    category: "스무디",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "딸기 추가", price: 250 },
      { id: 2, name: "바나나 추가", price: 200 },
      { id: 3, name: "꿀 추가", price: 150 },
      { id: 4, name: "아몬드 슬라이스 추가", price: 250 },
    ],
  },
  {
    id: 19,
    title: "망고스무디",
    price: 3500,
    img: images.mangoSm,
    category: "스무디",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "망고 조각 추가", price: 250 },
      { id: 2, name: "코코넛 조각 추가", price: 200 },
      { id: 3, name: "꿀 추가", price: 150 },
      { id: 4, name: "치아씨드 추가", price: 200 },
    ],
  },
  {
    id: 20,
    title: "망고바나나스무디",
    price: 4000,
    img: images.mangobananaSm,
    category: "스무디",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "과일 추가", price: 250 },
      { id: 2, name: "꿀 추가", price: 150 },
      { id: 3, name: "치아씨드 추가", price: 200 },
      { id: 4, name: "아몬드 슬라이스 추가", price: 250 },
    ],
  },
  {
    id: 21,
    title: "블루베리스무디",
    price: 4000,
    img: images.blueberrySm,
    category: "스무디",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "블루베리 추가", price: 250 },
      { id: 2, name: "바나나 추가", price: 200 },
      { id: 3, name: "꿀 추가", price: 150 },
      { id: 4, name: "치아씨드 추가", price: 200 },
    ],
  },
  {
    id: 22,
    title: "자몽스무디",
    price: 4000,
    img: images.grapefruitSm,
    category: "스무디",
    coffeeSize: ["regular", "large"],
    drinkOption: ["iced"],
    options: [
      { id: 1, name: "자몽 조각 추가", price: 250 },
      { id: 2, name: "레몬즙 추가", price: 150 },
      { id: 3, name: "꿀 추가", price: 150 },
      { id: 4, name: "치아씨드 추가", price: 200 },
    ],
  },
  {
    id: 23,
    title: "고구마라떼",
    price: 3000,
    img: images.sweetpotatoLa,
    category: "라떼&음료",
    coffeeSize: ["tall", "grande"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "견과류 추가", price: 250 },
      { id: 2, name: "시럽 추가", price: 150 },
      { id: 3, name: "시나몬 가루", price: 200 },
    ],
  },
  {
    id: 24,
    title: "녹차라떼",
    price: 3000,
    img: images.greenteaLa,
    category: "라떼&음료",
    coffeeSize: ["tall", "grande"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "견과류 추가", price: 250 },
      { id: 2, name: "아이스크림 추가", price: 300 },
      { id: 3, name: "휘핑크림 추가", price: 400 },
      { id: 4, name: "시럽 추가", price: 300 },
    ],
  },
  {
    id: 25,
    title: "단호박라떼",
    price: 3000,
    img: images.pumpkinLa,
    category: "라떼&음료",
    coffeeSize: ["tall", "grande"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "견과류 추가", price: 250 },
      { id: 2, name: "시럽 추가", price: 200 },
      { id: 3, name: "시나몬 가루", price: 200 },
    ],
  },
  {
    id: 26,
    title: "오곡라떼",
    price: 3000,
    img: images.fivegrainLa,
    category: "라떼&음료",
    coffeeSize: ["tall", "grande"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "견과류 추가", price: 250 },
      { id: 2, name: "시럽 추가", price: 150 },
      { id: 3, name: "아이스크림 추가", price: 300 },
    ],
  },
  {
    id: 27,
    title: "아이스초코",
    price: 3000,
    img: images.icedchocolateLa,
    category: "라떼&음료",
    coffeeSize: ["tall", "grande"],
    drinkOption: ["hot", "iced"],
    options: [
      { id: 1, name: "시럽 추가", price: 300 },
      { id: 2, name: "휘핑크림 추가", price: 400 },
      { id: 3, name: "초코칩 추가", price: 300 },
    ],
  },
  {
    id: 28,
    title: "딸기티",
    price: 3000,
    img: images.strawberryTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "딸기 추가", price: 500 },
      { id: 2, name: "딸기 시럽", price: 300 },
      { id: 3, name: "레몬 조각 추가", price: 200 },
    ],
  },
  {
    id: 29,
    title: "레몬티",
    price: 3000,
    img: images.lemonTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "레몬 조각 추가", price: 200 },
      { id: 2, name: "시럽 추가", price: 150 },
      { id: 3, name: "민트 잎 추가", price: 150 },
    ],
  },
  {
    id: 30,
    title: "밀크티",
    price: 3500,
    img: images.milkTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "타피오카 펄 추가", price: 250 },
      { id: 2, name: "휘핑크림 추가", price: 250 },
      { id: 3, name: "시럽 추가", price: 200 },
    ],
  },
  {
    id: 31,
    title: "애플시나몬티",
    price: 3500,
    img: images.applecinnamonTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "애플 조각 추가", price: 200 },
      { id: 2, name: "시나몬 추가", price: 150 },
      { id: 3, name: "시럽 추가", price: 150 },
    ],
  },
  {
    id: 32,
    title: "얼그레이",
    price: 3000,
    img: images.earlgreyTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "레몬 추가", price: 150 },
      { id: 2, name: "꿀 추가", price: 150 },
      { id: 3, name: "민트 잎 추가", price: 150 },
    ],
  },
  {
    id: 33,
    title: "유스베리티",
    price: 3500,
    img: images.blueberryTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "베리 추가", price: 200 },
      { id: 2, name: "시럽 추가", price: 150 },
      { id: 3, name: "레몬 추가", price: 150 },
    ],
  },
  {
    id: 34,
    title: "유자피나콜라다티",
    price: 3500,
    img: images.yuzupinacoladaTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "유자 조각 추가", price: 200 },
      { id: 2, name: "코코넛 조각 추가", price: 250 },
      { id: 3, name: "시럽 추가", price: 150 },
    ],
  },
  {
    id: 35,
    title: "캐모마일티",
    price: 3000,
    img: images.chamomileTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "시럽 추가", price: 150 },
      { id: 2, name: "레몬 추가", price: 150 },
      { id: 3, name: "민트 잎 추가", price: 150 },
    ],
  },
  {
    id: 36,
    title: "허니자몽블랙티",
    price: 3500,
    img: images.joneyjasmineblackTea,
    category: "티",
    coffeeSize: ["regular"],
    drinkOption: ["hot"],
    options: [
      { id: 1, name: "자몽 조각 추가", price: 300 },
      { id: 2, name: "시럽 추가", price: 200 },
      { id: 3, name: "레몬 조각 추가", price: 200 },
    ],
  },
];
export default data;

// export const jsonData = JSON.stringify(data, null, 2);
